version: '3.1'

services:

  ufc-web-mongo:
    image: mongo:4.4.6
    volumes:
      - ufcwebmongodata:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpwd

volumes:
  ufcwebmongodata:
